import { Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './components/menu/navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <body>

      <Typography>hOLA</Typography>
    
      
     </body>

    </div>
  )
}

